import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useOps } from '../../context/OpsContext';
import { FileText, Download, Copy, Check, RefreshCw } from 'lucide-react';
import { api } from '../../services/api';
import { ErrorState } from '../ui/ErrorState';

const fmtDateTime = (iso: string | null | undefined) => {
  if (!iso) return '—';
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? '—' : d.toLocaleString();
};

export const ReportsView: React.FC = () => {
  const { systemSummary, theme, notify } = useOps();
  const isDark = theme === 'dark';
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<unknown>(null);
  const [report, setReport] = useState<{ report: string; generatedAt: string } | null>(null);
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setReport(await api.getDailyReport());
    } catch (e) {
      setError(e);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => () => { if (copyTimer.current) clearTimeout(copyTimer.current); }, []);

  const handleCopy = async () => {
    if (!report) return;
    try {
      await navigator.clipboard.writeText(report.report);
      setCopied(true);
      if (copyTimer.current) clearTimeout(copyTimer.current);
      copyTimer.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      notify('error', 'Could not copy to the clipboard');
    }
  };

  const handleDownload = () => {
    if (!report) return;
    const url = URL.createObjectURL(new Blob([report.report], { type: 'text/plain;charset=utf-8' }));
    const a = document.createElement('a');
    a.href = url;
    const stamp = (report.generatedAt && !Number.isNaN(Date.parse(report.generatedAt)) ? report.generatedAt : new Date().toISOString()).slice(0, 10);
    a.download = `scholario-ops-report-${stamp}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 0);
  };

  const card = `p-3 rounded border ${isDark ? 'bg-[#111726] border-[#1E293B]' : 'bg-white border-slate-200 shadow-xs'}`;
  const label = `text-[10px] uppercase ${isDark ? 'text-slate-400' : 'text-slate-500'}`;
  const value = `text-base font-bold tabular-nums mt-0.5 ${isDark ? 'text-slate-100' : 'text-slate-900'}`;
  const ratio = (a: number, b: number) => (b === 0 ? '—' : `${a} / ${b}`);

  const btnBase = `flex items-center gap-1.5 px-3 py-1.5 rounded transition-colors border cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed`;

  return (
    <div className="space-y-5">
      <div className={`flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b ${isDark ? 'border-[#1E293B]' : 'border-slate-200'}`}>
        <div>
          <h1 className="text-lg font-bold font-mono tracking-tight">DAILY OPERATIONS REPORT</h1>
          <p className={`text-xs font-mono mt-0.5 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>
            Generated by the server from live data · {report ? `generated ${fmtDateTime(report.generatedAt)}` : loading ? 'loading…' : 'not available'}
          </p>
        </div>
        <div className="flex items-center gap-2 font-mono text-xs">
          <button
            onClick={() => void load()}
            disabled={loading}
            className={`${btnBase} ${isDark ? 'bg-[#111726] border-[#1E293B] text-slate-300 hover:text-white' : 'bg-white border-slate-300 text-slate-700 hover:bg-slate-50 shadow-xs'}`}
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span>REGENERATE</span>
          </button>
          <button
            onClick={() => void handleCopy()}
            disabled={!report}
            className={`${btnBase} ${isDark ? 'bg-[#111726] border-[#1E293B] text-slate-300 hover:text-white' : 'bg-white border-slate-300 text-slate-700 hover:bg-slate-50 shadow-xs'}`}
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'COPIED' : 'COPY'}</span>
          </button>
          <button
            onClick={handleDownload}
            disabled={!report}
            className={`${btnBase} bg-blue-600 border-blue-600 text-white hover:bg-blue-700 shadow-xs font-semibold`}
          >
            <Download className="w-3.5 h-3.5" />
            <span>DOWNLOAD .TXT</span>
          </button>
        </div>
      </div>

      {/* Live summary from the current dashboard state */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-xs font-mono">
        <div className={card}>
          <div className={label}>Applications healthy</div>
          <div className={value}>{ratio(systemSummary.healthyApps, systemSummary.totalApps)}</div>
        </div>
        <div className={card}>
          <div className={label}>Servers healthy</div>
          <div className={value}>{ratio(systemSummary.healthyServers, systemSummary.totalServers)}</div>
        </div>
        <div className={card}>
          <div className={label}>Monitors healthy</div>
          <div className={value}>{ratio(systemSummary.healthyMonitors, systemSummary.totalMonitors)}</div>
        </div>
        <div className={card}>
          <div className={label}>Open incidents</div>
          <div className={`text-base font-bold tabular-nums mt-0.5 ${systemSummary.criticalIncidents > 0 ? 'text-rose-500' : systemSummary.openIncidents > 0 ? 'text-amber-500' : isDark ? 'text-slate-100' : 'text-slate-900'}`}>
            {systemSummary.openIncidents}
            {systemSummary.criticalIncidents > 0 && <span className="text-[11px] font-semibold ml-1.5">({systemSummary.criticalIncidents} critical)</span>}
          </div>
        </div>
        <div className={card}>
          <div className={label}>DR ready</div>
          <div className={value}>{ratio(systemSummary.drReadinessCount, systemSummary.totalApps)}</div>
        </div>
        <div className={card}>
          <div className={label}>Successful backups (26h)</div>
          <div className={value}>{systemSummary.backupsCurrentCount}</div>
        </div>
        <div className={card}>
          <div className={label}>Cloudflare</div>
          <div className={`text-base font-bold mt-0.5 ${systemSummary.cloudflareStatus === 'HEALTHY' ? 'text-emerald-500' : 'text-amber-500'}`}>{systemSummary.cloudflareStatus}</div>
        </div>
        <div className={card}>
          <div className={label}>Overall</div>
          <div className={`text-base font-bold mt-0.5 ${systemSummary.overallHealth === 'OPERATIONAL' ? 'text-emerald-500' : systemSummary.overallHealth === 'WARNING' ? 'text-amber-500' : 'text-rose-500'}`}>{systemSummary.overallHealth}</div>
        </div>
      </div>

      <div className={`rounded-lg border p-5 space-y-3 font-mono transition-colors ${isDark ? 'bg-[#111726] border-[#1E293B]' : 'bg-white border-slate-200 shadow-xs'}`}>
        <div className={`flex items-center justify-between border-b pb-2 text-xs ${isDark ? 'border-[#1A2332]' : 'border-slate-100'}`}>
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-500" />
            <h2 className="font-bold">REPORT TEXT</h2>
          </div>
          {loading && <RefreshCw className="w-3 h-3 text-blue-400 animate-spin" />}
        </div>
        {error && !loading ? (
          <ErrorState error={error} onRetry={() => void load()} />
        ) : !report ? (
          <div className={`p-6 text-center text-xs ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>
            {loading ? 'Generating report…' : 'No report available.'}
          </div>
        ) : (
          <pre className={`p-4 rounded border text-xs leading-relaxed overflow-x-auto whitespace-pre-wrap ${isDark ? 'bg-[#080B12] text-slate-300 border-[#182338]' : 'bg-slate-900 text-emerald-300 border-slate-800'}`}>
            {report.report}
          </pre>
        )}
      </div>
    </div>
  );
};
